Maskable component
ToyotaResearchInstitute/lakefront pull request #188
Opened 2021-11-09 20:31 UTC by NehalBhandariSlalom

This PR includes Maskable Component which renders an image. The image can be highlighted, selected and shows spinner until the image is loaded. This can be achieved by setting the appropriate properties.
<img width="429" alt="Screen Shot 2021-11-09 at 2 08 21 PM" src="https://user-images.githubusercontent.com/30271951/141000036-abe80af7-0ad8-4eb4-adc0-872b97031ae8.png">
<img width="1010" alt="Screen Shot 2021-11-09 at 3 10 21 PM" src="https://user-images.githubusercontent.com/30271951/141000040-8a061f0c-3de2-4069-9dc1-8fa639c8ba31.png">

2021-11-09 20:36 UTC, amirkibbar approved these changes

2021-11-09 20:49 UTC, jason-ransom-slalom requested changes
The component needs to be exported from the primary index file as well.

2021-11-09 20:49 UTC, jason-ransom-slalom commented on package.json
> +  "version": "0.82.5",
Bump version to at least 0.83.0.
Btw: If you want the version to be bumped for you, you can include "feature" in at least one of your PRs (https://github.com/ToyotaResearchInstitute/lakefront/blob/main/CONTRIBUTING.md#versioning)

2021-11-09 20:49 UTC, jason-ransom-slalom commented on src/MaskableImage/assets/checkedOutline.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L
nit: Add new line here.

2021-11-09 20:49 UTC, jason-ransom-slalom commented on src/MaskableImage/maskableImageStyles.ts
> +)
nit: Add new line here.

2021-11-09 20:52 UTC, adorack-tri requested changes
For the image (nature.jpg), I think it would make sense to reduce the quality in order to reduce the file size.  I'll send an example via Slack.

2021-11-09 20:52 UTC, adorack-tri commented on src/MaskableImage/MaskableImage.tsx
> + * This Component is used to render an image. The image can be selected and highlighted.The showSpinnerOnLoad when set
Minor: there should be a space between '.' and 'The'.

2021-11-09 20:52 UTC, adorack-tri commented on src/MaskableImage/MaskableImage.tsx
> +    // const aspectRatioConstraint = { paddingBottom: `${heightToWidthRatio * 100}%` };
Please remove dead code.

2021-11-09 21:40 UTC, jason-ransom-slalom approved these changes

2021-11-10 14:46 UTC, NehalBhandariSlalom commented
> For the image (nature.jpg), I think it would make sense to reduce the quality in order to reduce the file size. I'll send an example via Slack.

I have uploaded a lower quality image. Please check if this looks good.

2021-11-10 14:58 UTC, adorack-tri approved these changes

2021-11-10 15:00 UTC, merged