Tabs component
ToyotaResearchInstitute/lakefront pull request #197
Opened 2021-11-29 23:14 UTC by NehalBhandariSlalom

This PR includes Tabs core component moved into Lakefront and then replace usage in Lakehouse for easier maintenance and better documentation.
If approved, this will close #196.
![Screen Shot 2021-11-29 at 6 08 01 PM](https://user-images.githubusercontent.com/30271951/143957425-04f6a6b7-9779-4c52-84a1-5332ac32a80e.png)

2021-11-30 14:43 UTC, jason-ransom-slalom requested changes

2021-11-30 14:43 UTC, jason-ransom-slalom commented on src/Tabs/Tabs.tsx
> +     * This is to set the slected tab by default.
Mispelled "selected"

2021-11-30 14:43 UTC, jason-ransom-slalom commented on src/Tabs/__tests__/Tabs.tests.jsx
> +import Immutable from 'immutable';
Immutable import needs to be removed.

2021-11-30 14:43 UTC, jason-ransom-slalom commented on src/Tabs/__tests__/Tabs.tests.jsx
> +const TABS = Immutable.List([
Immutable use here needs to be removed.

2021-11-30 14:48 UTC, jason-ransom-slalom requested changes

2021-11-30 14:48 UTC, jason-ransom-slalom commented on src/Tabs/Tabs.tsx
> +import React from 'react';
Remove React import and only import what you need to be consistent with rest of application.

2021-11-30 14:48 UTC, jason-ransom-slalom commented on src/Tabs/Tabs.tsx
> +const Tabs: React.FC<TabProps> = props => {
import { FC } from React above and change this line to be:
```jsx
const Tabs: FC<TabProps> = props => {
```

2021-11-30 14:48 UTC, jason-ransom-slalom commented on src/index.ts
> +export { default as Tabs } from './Tabs';
You might also export the associate Tab typescript types (specifically the TabDef) I believe. See how other types are exported in this file if you need a reference.

2021-12-01 16:18 UTC, adorack-tri approved these changes

2021-12-01 17:23 UTC, jason-ransom-slalom approved these changes

2021-12-01 17:23 UTC, jason-ransom-slalom commented on src/types/global.ts
> +}
nit: Add new line here.

2021-12-01 17:28 UTC, merged