Origin/main/speed input/component
ToyotaResearchInstitute/lakefront pull request #232
Opened 2022-02-28 22:06 UTC by alex-maul

Added SpeedInput with storybook and tests

![Screen Shot 2022-02-28 at 5 03 28 PM](https://user-images.githubusercontent.com/87024084/156066021-bfd2e14a-8f3d-4446-8abc-604ff511e0f6.png)

2022-03-01 14:42 UTC, NehalBhandariSlalom requested changes

2022-03-01 14:42 UTC, NehalBhandariSlalom commented on src/SpeedInput/SpeedInput.tsx
> +
Remove the extra line here. line 89

2022-03-01 14:42 UTC, NehalBhandariSlalom commented on src/SpeedInput/speedInputStyles.ts
> +export const RadioGroupWrapper = styled.div({
We need to pass theme here like in other style components. styled.div(({theme})=>

2022-03-01 14:42 UTC, NehalBhandariSlalom commented on src/SpeedInput/SpeedInput.tsx
> +
Import theme and theme provider as we used in other components.
import { ThemeProvider } from '@emotion/react';
import theme from 'src/styles/theme';

2022-03-01 14:59 UTC, NehalBhandariSlalom requested changes

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/SpeedInput/SpeedInput.tsx
> +        <div>
Wrap the component with Theme Provider as done in other components like this <ThemeProvider theme={theme}>

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/SpeedInput/SpeedInput.tsx
> +    });
Ad a line between line 62 and 63.

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/SpeedInput/SpeedInput.tsx
> +}
Please add documentation for SpeedInput Component. A description about what this component would do. For reference, check other components.

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/stories/SpeedInput.stories.tsx
> +    };
Please add the function. May be just create a state and update that state to show a message whenever the change event is triggered. Check Refreshtoolbar implementation.

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/stories/SpeedInput.stories.tsx
> +import { ComponentPropsWithoutRef } from 'react';
The SpeedInput.Stories.tsx file should be inside the SpeedInput folder so that the path would be. "src/stories/SpeedInput"

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/SpeedInput/_tests_/SpeedInput.test.jsx
> +        expect(speedInputContainer).toBeDisabled;
toBeDisabled is a function. Please replace it with this   expect(speedInputContainer).toBeDisabled();

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/SpeedInput/_tests_/SpeedInput.test.jsx
> +        expect(container).toBeInTheDocument;
toBeInTheDocument is a function. Please replace it with this expect(container).toBeInTheDocument();

2022-03-01 14:59 UTC, NehalBhandariSlalom commented on src/SpeedInput/_tests_/SpeedInput.test.jsx
> +        expect(icon).toBeDefined;
toBeDefined is a function. Please replace it with  expect(icon).toBeDefined();

2022-03-01 18:26 UTC, amirkibbar approved these changes

2022-03-01 18:38 UTC, adorack-tri approved these changes
(Though please see one minor comment.)

2022-03-01 18:38 UTC, adorack-tri commented on src/SpeedInput/SpeedInput.tsx
> +    *  TODO:
What's the `TODO` item here?

2022-03-01 18:55 UTC, alex-maul commented on src/SpeedInput/SpeedInput.tsx
> +    *  TODO:
Forgotten to remove this. Thanks!

2022-03-04 16:51 UTC, NehalBhandariSlalom requested changes
In the stotybook, try clearing the min and max values- The values are not getting cleared. Please check.

2022-03-04 19:16 UTC, NehalBhandariSlalom approved these changes
Approved!!

2022-03-04 19:19 UTC, merged