Drive 73463 Make Lakefront Tables sortable on multiple columns
ToyotaResearchInstitute/lakefront pull request #238
Opened 2022-05-25 21:05 UTC by VilasiniS

Description:
Updated [Lakefront table](https://toyotaresearchinstitute.github.io/lakefront/?path=%2Fdocs%2Flakefront-table--table) to support:

The table allows sorting by multiple columns (ascending and descending).
The table accepts a parameter setting the default sort.
Users can apply multiple sort criteria by shift-clicking on the columns.
A tooltip on the title indicates that multiple sort criteria are possible by shift-clicking to add to the sort.
Accepts width as a parameter.

2022-05-25 21:07 UTC, VilasiniS commented
Sorting applied on Percentage change and value columns:

![Screen Shot 2022-05-25 at 5 06 51 PM](https://user-images.githubusercontent.com/89927521/170367379-259a284e-d992-4403-bb10-375976c3c33e.png)

2022-05-26 13:07 UTC, jason-ransom-slalom requested changes

2022-05-26 13:07 UTC, jason-ransom-slalom commented on src/Table/tableStyles.ts
> +        svg:{
nit: add space after svg:

2022-05-26 13:07 UTC, jason-ransom-slalom commented on src/Table/tableStyles.ts
> +    paddingLeft:5,
nit add spaces after colons.

2022-05-26 13:07 UTC, jason-ransom-slalom commented on src/Table/tableStyles.ts
> +    marginLeft:8,
nit add spaces after colons.

2022-05-26 13:07 UTC, jason-ransom-slalom commented on src/Table/tableStyles.ts
> +export const StyledHeader = styled.div({
nit: add spaces after colons throughout

2022-05-26 13:07 UTC, jason-ransom-slalom commented on src/Table/Table.tsx
> +                                            ))
Thinking more about this, I think we need to determine if the `disableMultiSort` option is passed to determine which tooltip message we should show --- i.e., if it is `true`, we should show the normal props.title... but it if is `false`, we should show the message above.

2022-05-26 13:07 UTC, jason-ransom-slalom commented on src/stories/Table/Table.stories.tsx
> +        disableMultiSort: false
Let's add two more stories here to show:
1.) when multisort is enabled
2.) when custom widths are passed.

2022-05-26 13:09 UTC, jason-ransom-slalom commented on src/Table/Table.tsx
> +                                            { title: 'Hold shift & click the column to add to multi-sort', width:column.width },
Yeah you'll need to use the callback version to implement the `disableMultiSort` logic I mention below.

2022-05-26 18:08 UTC, jason-ransom-slalom approved these changes

2022-05-27 14:13 UTC, closed without merging