Drive 53097 create radio button component
ToyotaResearchInstitute/lakefront pull request #47
Opened 2021-04-23 21:33 UTC by zach-jones-slalom

![image](https://user-images.githubusercontent.com/80778912/115931873-883df480-a451-11eb-9092-188eb4604b77.png)

This PR adds a radio group comp to lakefront.

Still need to write unit tests.

2021-04-23 21:42 UTC, michaelpuzon approved these changes

2021-04-26 15:14 UTC, jason-ransom-slalom requested changes
You'll want to export and add the new comment to the documentation. [See these steps](https://github.com/ToyotaResearchInstitute/lakefront/blob/main/CONTRIBUTING.md#adding-new-components)

2021-04-26 15:14 UTC, jason-ransom-slalom commented on src/RadioGroup/RadioGroup.tsx
> +
Add a new line at the end of the file.

2021-04-26 15:14 UTC, jason-ransom-slalom commented on src/RadioGroup/assets/radioChecked.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 7c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24
Add a new line at the end of the file.

2021-04-26 15:14 UTC, jason-ransom-slalom commented on src/RadioGroup/assets/radioUnchecked.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-1
Add a new line at the end of the file.

2021-04-26 15:17 UTC, jason-ransom-slalom commented on src/RadioGroup/RadioGroup.tsx
> +
Oh! And @zach-jones-slalom, the branch name should be renamed.

2021-04-26 15:18 UTC, jason-ransom-slalom commented
Completing this PR will close #48

2021-04-26 15:28 UTC, closed without merging